[package]
name = "par-stream"
description = "Asynchronous parallel streams analogous to rayon"
version = "0.3.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
categories = ["asynchronous"]
documentation = "https://docs.rs/par-stream/"
repository = "https://github.com/jerry73204/par-stream.git"
homepage = "https://github.com/jerry73204/par-stream"
readme = "README.md"
license = "MIT"

[dependencies]
futures = "0.3.12"
num_cpus = "1.13.0"
async-std = { version = "1.9.0", optional = true }
tokio = { version = "1.1.1", features = ["rt-multi-thread"], optional = true }
pin-project = "1.0.5"
derivative = "2.2.0"

[dev-dependencies]
rand = "0.8.3"
async-std = { version = "1.9.0", features = ["unstable", "attributes"] } # for doc tests

[features]
runtime_async-std = ["async-std", "async-std/unstable", "async-std/attributes", "tokio", "tokio/sync", "tokio/macros"]
runtime_tokio = ["tokio", "tokio/sync", "tokio/macros", "async-std", "async-std/unstable"]
doc-only = ["runtime_async-std"]

[package.metadata.docs.rs]
features = ["doc-only"]
no-default-features = true
