[package]
name = "par-stream"
version = "0.2.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
num_cpus = "1.13"
async-std = { version = "1.7", features = ["unstable", "attributes"] }
tokio = { version = "0.3", features = ["sync", "macros"] }
pin-project = "1.0"
derivative = "2.1"

[dev-dependencies]
rand = "0.7"
tokio = { version = "0.3", features = ["sync", "macros", "rt-multi-thread"] }
